version: '3'

services:
  db:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    
  web:
    build: .
    container_name: docker-php
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db